// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220104131223_receptionist")]
    partial class receptionist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataLayer.Models.Guest", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("ID");

                    b.Property<string>("IDCardNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("ID_card_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Surname");

                    b.HasKey("ID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("DataLayer.Models.Receptionist", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.HasKey("Email");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("DataLayer.Models.Reservation", b =>
                {
                    b.Property<string>("GuestID")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Guest_ID");

                    b.Property<int>("HotelRoomNumber")
                        .HasColumnType("int")
                        .HasColumnName("Hotel_Room_Number");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CheckIn_date");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CheckOut_date");

                    b.HasKey("GuestID", "HotelRoomNumber", "CheckInDate");

                    b.HasIndex("HotelRoomNumber");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DataLayer.Models.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int")
                        .HasColumnName("Room_Number");

                    b.Property<int>("RoomSize")
                        .HasColumnType("int")
                        .HasColumnName("Room_Size");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Room_Type");

                    b.HasKey("RoomNumber");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DataLayer.Models.Reservation", b =>
                {
                    b.HasOne("DataLayer.Models.Guest", "HotelGuest")
                        .WithMany()
                        .HasForeignKey("GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Room", "HotelRoom")
                        .WithMany()
                        .HasForeignKey("HotelRoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelGuest");

                    b.Navigation("HotelRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
